on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: eifinger/setup-rye@v2
      - run: rye pin 3.12
      - run: rye sync
      - name: generate docs
        run: rye run pdoc pytest_robotframework -o docs
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/
      - uses: actions/deploy-pages@v2
