on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: ./pw pdm install --group=docs
      - name: generate docs
        run: ./pw pdm run pdoc pytest_robotframework -o docs
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/
      - uses: actions/deploy-pages@v2
